/* ============================================================================
   AIVA — export.js
   Builds the business case document and the two downloads.

   Word:  a Word-compatible HTML document (Office HTML) delivered as a .doc
          Blob. Opens natively in Microsoft Word and Google Docs with styles,
          tables and the AIVA brand band intact — no library, no server.
   PDF:   the browser print path against the print stylesheet, which is scoped
          to render only the business case. "Save as PDF" produces an
          executive-ready document.

   The on-screen business case (app.js) and the Word file share one builder, so
   what you review is what you export.
   ============================================================================ */

window.AIVA = window.AIVA || {};

(function (AIVA) {
  'use strict';

  const esc = (s) => AIVA.fmt.escapeHtml(s);
  const fmt = () => AIVA.fmt;

  /* --------------------------------------------------------------------------
     Narrative generators — the "generated by AI" sections of the case.
     ----------------------------------------------------------------------- */

  function futureState(state, analysis, r) {
    const pattern = state.discovery.agenticPattern && state.discovery.agenticPattern !== 'Unsure'
      ? state.discovery.agenticPattern : (analysis.agenticPattern || 'agentic solution');
    const wf = state.discovery.workflowName || 'the workflow';
    const timeSaved = state.drivers.productivity.on ? Math.round(state.drivers.productivity.timeSaved) : 0;
    const parts = [];
    parts.push(`In the target state, ${lc(wf)} is delivered as ${article(pattern)} ${lc(pattern)}. The agent gathers the information currently assembled by hand, applies the documented rules and policy, and produces the output for human review rather than human authorship.`);
    if (timeSaved) parts.push(`Hands-on effort per case falls by an estimated ${timeSaved}%, returning ${fmt().number(r.ben.hoursSaved)} hours a year to the ${fmt().number(state.current.peopleInvolved)}-person team. People move from producing the work to checking and improving it — the pattern that lets the organisation absorb more volume without adding headcount.`);
    if (state.suitability.approvals || state.suitability.checkableOutcomes) {
      parts.push(`Decisions that carry legal, financial or reputational weight remain with a person. The agent records the evidence behind every step, so the process becomes more auditable than it is today, not less.`);
    }
    return parts;
  }

  function opportunity(state, analysis, r) {
    const top = analysis.signals.slice(0, 3).map((s) => lc(s.label));
    const parts = [];
    parts.push(analysis.signals.length
      ? `AIVA's reading of the workflow evidences ${list(top)}. These are the characteristics that make agentic AI the right instrument rather than classic automation, and they place this workflow at ${Math.round(r.fit.score)} out of 100 on the agentic fit scale — a ${lc(r.fit.band.label)}.`
      : `On the structured answers, the workflow scores ${Math.round(r.fit.score)} out of 100 on the agentic fit scale (${lc(r.fit.band.label)}).`);
    if (r.fit.strongest.length) {
      parts.push(`The strongest signals are ${list(r.fit.strongest.slice(0, 3).map((d) => lc(d.label)))}, which is where the agent should be pointed first.`);
    }
    if (r.fit.band.label === 'Traditional Automation Better') {
      parts.push('On balance, however, the workflow lacks the reasoning and document load that justify an agent. The recommendation is to capture the value through integration or process simplification instead.');
    }
    return parts;
  }

  /* --------------------------------------------------------------------------
     The document body — one HTML string, used on screen and in the Word file.
     `mode` is 'screen' or 'word'; Word gets inline styles Office understands.
     ----------------------------------------------------------------------- */

  function buildBody(state, r, analysis, mode) {
    const w = mode === 'word';
    const H3 = (t) => w ? `<h3 style="font-family:Segoe UI,Arial,sans-serif;font-size:13pt;color:#141414;border-bottom:1px solid #d9d9d4;padding-bottom:4pt;margin:18pt 0 8pt;">${esc(t)}</h3>`
      : `<h3>${esc(t)}</h3>`;
    const P = (t) => w ? `<p style="margin:0 0 8pt;color:#333;font-size:10.5pt;line-height:1.5;">${t}</p>` : `<p>${t}</p>`;
    const section = (inner) => w ? `<div style="margin-bottom:14pt;">${inner}</div>` : `<div class="doc-section">${inner}</div>`;

    const paras = (arr) => arr.map((t) => P(esc(t))).join('');
    const freeText = (text) => fmt().paragraphs(text).map((p) => P(esc(p))).join('') || P('<em>Not provided.</em>');

    let html = '';

    /* Executive summary */
    html += section(H3('Executive summary') + P(
      `<strong>${esc(r.rec.verdict)}.</strong> ${esc(r.rec.stance)}`) +
      P(`The assessment values ${lc(state.discovery.workflowName || 'the workflow')} at an estimated <strong>${esc(fmt().money(r.ben.annualBenefit))}</strong> in annual benefit at full run rate, against a total investment of ${esc(fmt().money(r.fin.totalInvestment))} over ${r.fin.horizon} years. This returns an ROI of <strong>${esc(fmt().percent(r.fin.roi))}</strong>, an NPV of ${esc(fmt().money(r.fin.npv))} and payback in ${esc(fmt().months(r.fin.paybackMonths))}, at a stated confidence of ${Math.round(r.conf.score)}%.`));

    /* Business challenge (from free text) */
    html += section(H3('Business challenge') + freeText(state.discovery.problem));

    /* Current state */
    const b = r.base;
    html += section(H3('Current state') +
      freeText(state.discovery.currentWorkflow) +
      P(`In numbers: the workflow runs <strong>${fmt().number(b.casesPerYear)}</strong> times a year at an average of ${fmt().number(state.current.minutesPerTransaction)} minutes per case, consuming <strong>${fmt().number(b.hoursPerYear)} hours</strong> — about ${b.fteConsumed.toFixed(1)} full-time equivalents — at a fully-burdened cost of ${esc(fmt().money(b.labourCost))} a year. The work touches ${esc(state.current.systemsBand)} systems with ${esc(state.current.handoffsBand.toLowerCase())} handoffs, and current pain is rated ${state.current.painLevel} of 5.`));

    /* Future state (generated) */
    html += section(H3('Future state') + paras(futureState(state, analysis, r)));

    /* Agentic AI opportunity (generated) */
    html += section(H3('Agentic AI opportunity') + paras(opportunity(state, analysis, r)));

    /* Expected benefits table */
    const rows = r.ben.lines.filter((l) => l.on && l.value > 0)
      .map((l) => `<tr><td style="${w ? tdL(w) : ''}">${esc(l.label)}</td><td style="${tdR(w)}">${esc(fmt().money(l.value))}</td><td style="${tdL(w)}">${esc(l.basis)}</td></tr>`).join('');
    const strat = state.drivers.strategic.on
      ? `<tr><td style="${tdL(w)}">Strategic</td><td style="${tdR(w)}">Qualitative</td><td style="${tdL(w)}">${esc(state.drivers.strategic.benefits.join(', ') || 'Innovation and long-term capability')}</td></tr>` : '';
    html += section(H3('Expected benefits') +
      `<table style="${tableStyle(w)}"><thead><tr><th style="${thL(w)}">Benefit</th><th style="${thR(w)}">Annual value</th><th style="${thL(w)}">Basis</th></tr></thead><tbody>${rows}${strat}</tbody><tfoot><tr><td style="${tfL(w)}">Total quantified</td><td style="${tfR(w)}">${esc(fmt().money(r.ben.annualBenefit))}</td><td style="${tfL(w)}"></td></tr></tfoot></table>` +
      (r.ben.capacityHours > 0 ? P(`<strong>Capacity returned:</strong> ${fmt().number(r.ben.capacityHours)} hours a year — equivalent to ${r.ben.capacityFte.toFixed(1)} FTE — released to higher-value work without removing staff.`) : ''));

    /* Investment & returns */
    html += section(H3('Investment required') +
      `<table style="${tableStyle(w)}"><tbody>` +
      kv(w, 'Implementation', fmt().money(state.invest.implementation)) +
      kv(w, 'Change & adoption', fmt().money(state.invest.changeCost)) +
      kv(w, 'Annual run cost', fmt().money(state.invest.annualRun)) +
      kv(w, `Total over ${r.fin.horizon} years`, fmt().money(r.fin.totalInvestment)) +
      '</tbody></table>' +
      `<table style="${tableStyle(w)};margin-top:10pt"><tbody>` +
      kv(w, 'Return on investment', fmt().percent(r.fin.roi)) +
      kv(w, 'Payback period', fmt().months(r.fin.paybackMonths)) +
      kv(w, 'Net present value', fmt().money(r.fin.npv)) +
      (r.fin.irr !== null ? kv(w, 'Internal rate of return', fmt().percent(r.fin.irr)) : '') +
      kv(w, 'Confidence score', Math.round(r.conf.score) + '%') +
      '</tbody></table>');

    /* Scores */
    html += section(H3('Assessment scores') +
      `<table style="${tableStyle(w)}"><tbody>` +
      kv(w, 'Agentic AI fit score', Math.round(r.fit.score) + ' / 100 — ' + r.fit.band.label) +
      kv(w, 'Business value score', Math.round(r.value.score) + ' / 100') +
      kv(w, 'Investment score', Math.round(r.invest.score) + ' / 100') +
      kv(w, 'Confidence score', Math.round(r.conf.score) + ' / 100') +
      '</tbody></table>');

    /* Recommendation */
    const actions = r.rec.actions.map((a) => w
      ? `<li style="margin:0 0 5pt;color:#333;font-size:10.5pt;line-height:1.5;">${esc(a)}</li>`
      : `<li>${esc(a)}</li>`).join('');
    html += section(H3('Recommendation') +
      P(`<strong>Proceed to: ${esc(r.rec.stage)}.</strong> ${esc(r.rec.stance)}`) +
      (w ? `<p style="margin:8pt 0 4pt;font-weight:600;font-size:10.5pt;">Next steps</p><ul style="margin:0;padding-left:16pt;">${actions}</ul>`
        : `<p style="font-weight:600;margin-bottom:.4rem">Next steps</p><ul>${actions}</ul>`));

    /* Sensitivity */
    const sens = r.sensitivity.map((sc) => `<tr><td style="${tdL(w)}">${esc(sc.label)}</td><td style="${tdR(w)}">${esc(fmt().percent(sc.roi))}</td><td style="${tdR(w)}">${esc(fmt().money(sc.npv))}</td><td style="${tdR(w)}">${esc(fmt().months(sc.payback))}</td></tr>`).join('');
    html += section(H3('Sensitivity') +
      P('How the return moves if the assumptions prove optimistic or conservative.') +
      `<table style="${tableStyle(w)}"><thead><tr><th style="${thL(w)}">Scenario</th><th style="${thR(w)}">ROI</th><th style="${thR(w)}">NPV</th><th style="${thR(w)}">Payback</th></tr></thead><tbody>${sens}</tbody></table>`);

    return html;
  }

  /* Inline-style helpers for the Word document. */
  function tableStyle(w) { return w ? 'border-collapse:collapse;width:100%;font-family:Segoe UI,Arial,sans-serif;font-size:10pt;margin:4pt 0;' : ''; }
  function thL(w) { return w ? 'text-align:left;background:#f2f2ef;border:1px solid #d9d9d4;padding:5pt 7pt;font-size:9pt;text-transform:uppercase;letter-spacing:.4pt;color:#555;' : ''; }
  function thR(w) { return w ? thL(w) + 'text-align:right;' : ''; }
  function tdL(w) { return w ? 'border:1px solid #d9d9d4;padding:5pt 7pt;color:#222;' : ''; }
  function tdR(w) { return w ? tdL(w) + 'text-align:right;font-variant-numeric:tabular-nums;' : ''; }
  function tfL(w) { return w ? 'border:1px solid #d9d9d4;padding:5pt 7pt;font-weight:700;background:#faf7f4;' : ''; }
  function tfR(w) { return w ? tfL(w) + 'text-align:right;' : ''; }
  function kv(w, k, v) { return `<tr><td style="${w ? 'border:1px solid #d9d9d4;padding:5pt 7pt;color:#333;' : ''}">${esc(k)}</td><td style="${tdR(w)}${w ? 'font-weight:600;' : ''}">${esc(v)}</td></tr>`; }

  function lc(s) { return String(s || '').charAt(0).toLowerCase() + String(s || '').slice(1); }
  function article(s) { return /^[aeiou]/i.test(s) ? 'an' : 'a'; }
  function list(items) { if (!items.length) return ''; if (items.length === 1) return items[0]; return items.slice(0, -1).join(', ') + ' and ' + items[items.length - 1]; }

  /* --------------------------------------------------------------------------
     Word file
     ----------------------------------------------------------------------- */

  function downloadWord(state, r, analysis) {
    const title = state.meta.caseName || 'Agentic AI Business Case';
    const cover = `
      <table style="width:100%;border-collapse:collapse;margin-bottom:16pt;">
        <tr><td style="background:#141414;padding:20pt 22pt;border-bottom:4pt solid #FF5800;">
          <div style="font-family:Segoe UI,Arial,sans-serif;font-size:8pt;letter-spacing:2pt;color:#FF5800;text-transform:uppercase;font-weight:700;">AIVA · Agentic AI Value Accelerator</div>
          <div style="font-family:Segoe UI,Arial,sans-serif;font-size:22pt;font-weight:700;color:#ffffff;margin-top:8pt;">${esc(title)}</div>
          <div style="font-family:Segoe UI,Arial,sans-serif;font-size:11pt;color:#dddddd;margin-top:6pt;">Business Case &amp; Value Assessment</div>
          <div style="font-family:Segoe UI,Arial,sans-serif;font-size:9pt;color:#bbbbbb;margin-top:12pt;">
            ${esc(state.meta.organisation || '')}${state.meta.organisation ? ' &nbsp;·&nbsp; ' : ''}${esc(state.discovery.workflowName || '')}<br/>
            ${state.meta.sponsor ? 'Sponsor: ' + esc(state.meta.sponsor) + ' &nbsp;·&nbsp; ' : ''}${state.meta.preparedBy ? 'Prepared by ' + esc(state.meta.preparedBy) + ' &nbsp;·&nbsp; ' : ''}${esc(fmt().today())}
          </div>
        </td></tr>
      </table>`;

    const doc =
      `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
      <head><meta charset="utf-8"><title>${esc(title)}</title>
      <!--[if gte mso 9]><xml><w:WordDocument><w:View>Print</w:View><w:Zoom>100</w:Zoom></w:WordDocument></xml><![endif]-->
      <style>@page{size:A4;margin:2cm;} body{font-family:'Segoe UI',Arial,sans-serif;color:#141414;}</style>
      </head><body>${cover}${buildBody(state, r, analysis, 'word')}
      <p style="margin-top:20pt;font-size:8pt;color:#999;border-top:1px solid #ddd;padding-top:6pt;">Generated by AIVA — Agentic AI Value Accelerator. Figures are estimates for investment triage and should be validated before funding. Confidence: ${Math.round(r.conf.score)}%.</p>
      </body></html>`;

    const blob = new Blob(['﻿', doc], { type: 'application/msword' });
    triggerDownload(blob, slug(title) + '.doc');
  }

  /* --------------------------------------------------------------------------
     PDF — print path
     ----------------------------------------------------------------------- */

  function downloadPdf() {
    window.print();
  }

  function triggerDownload(blob, filename) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1500);
  }

  function slug(s) {
    return String(s || 'business-case').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'business-case';
  }

  AIVA.exporter = { buildBody, downloadWord, downloadPdf, futureState, opportunity };
})(window.AIVA);
